---
name: AGP

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push@b87df265bdc149bc1771639e5b483b9e17f5980e
        with:
          username: ${{ env.GITHUB_ACTOR }}
          token: ${{ secrets.CI_TOKEN }}
