---
name: AGP

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push@c1749aa69a691327b0f204ce5cc20d43bd9668fd
        with:
          token: ${{ secrets.CI_TOKEN }}
