---
name: AGP

on:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: AGP
        uses: ms-jpq/auto-github-push@a9011528f1e6d565f21b215b1c45a8428841b617
        with:
          token: ${{ secrets.CI_TOKEN }}
